"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Search, X } from "lucide-react";
import { api } from "@/lib/client";
type Result = { id: string; title: string; subtitle: string; href: string };
export function GlobalSearch() {
  const [open, setOpen] = useState(false), [query, setQuery] = useState(""), [groups, setGroups] = useState<Record<string, Result[]>>({}), [loading, setLoading] = useState(false), [error, setError] = useState(""), [updatedAt, setUpdatedAt] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setOpen(true); } if (event.key === "Escape") setOpen(false); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, []);
  useEffect(() => { if (open) setTimeout(() => inputRef.current?.focus(), 50); }, [open]);
  useEffect(() => { if (query.trim().length < 2) { setGroups({}); setUpdatedAt(""); setLoading(false); return; } const controller = new AbortController(); const timer = setTimeout(async () => { setLoading(true); setError(""); try { const result = await api<{ groups: Record<string, Result[]>; generatedAt: string }>(`/api/search?q=${encodeURIComponent(query)}`, { signal: controller.signal }); setGroups(result.groups); setUpdatedAt(result.generatedAt); } catch (caught) { if ((caught as Error).name !== "AbortError") setError((caught as Error).message); } finally { setLoading(false); } }, 250); return () => { clearTimeout(timer); controller.abort(); }; }, [query]);
  const total = Object.values(groups).reduce((sum, items) => sum + items.length, 0);
  return <><button onClick={() => setOpen(true)} className="hidden min-w-56 items-center gap-2 rounded-xl border border-stone-200 bg-stone-50 px-3 py-2 text-sm text-stone-500 hover:bg-white md:flex"><Search size={16} /><span className="flex-1 text-left">Search Couture OS</span><kbd className="rounded border bg-white px-1.5 py-0.5 text-[10px]">⌘K</kbd></button><button aria-label="Search Couture OS" onClick={() => setOpen(true)} className="rounded-xl border border-stone-200 p-2.5 md:hidden"><Search size={18} /></button>{open && <div className="fixed inset-0 z-[80] flex items-start justify-center bg-ink/45 px-4 pt-[10vh] backdrop-blur-sm animate-fade-in" onMouseDown={(event) => event.currentTarget === event.target && setOpen(false)}><div className="w-full max-w-2xl overflow-hidden rounded-2xl border bg-white shadow-2xl animate-scale-in"><div className="flex items-center gap-3 border-b px-4"><Search size={20} className="text-stone-400" /><input ref={inputRef} value={query} onChange={(event) => setQuery(event.target.value)} className="border-0 px-0 py-4 text-base focus:ring-0" placeholder="Search customers, leads, orders, inventory, purchases..." /><button aria-label="Close" onClick={() => setOpen(false)} className="p-2"><X size={18} /></button></div><div className="max-h-[65vh] overflow-y-auto p-3">{query.length < 2 && <p className="p-8 text-center text-sm text-stone-400">Type at least two characters to search.</p>}{loading && <div className="space-y-2 p-2">{[1,2,3].map((item) => <div key={item} className="h-14 animate-pulse rounded-xl bg-stone-100" />)}</div>}{error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{!loading && query.length >= 2 && !error && total === 0 && <p className="p-8 text-center text-sm text-stone-400">No matching records found for your access.</p>}{!loading && Object.entries(groups).map(([label, items]) => items.length ? <section key={label} className="mb-4"><h3 className="px-2 py-1 text-[10px] font-bold uppercase tracking-[.18em] text-stone-400">{label}</h3>{items.map((item) => <Link key={`${label}-${item.id}`} href={item.href} onClick={() => setOpen(false)} className="block rounded-xl px-3 py-2.5 hover:bg-stone-50"><p className="text-sm font-semibold">{item.title}</p><p className="mt-0.5 truncate text-xs text-stone-500">{item.subtitle}</p></Link>)}</section> : null)}{updatedAt&&!loading&&<p className="border-t px-2 pt-3 text-[11px] text-stone-400">Last synced {new Date(updatedAt).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})}</p>}</div></div></div>}</>;
}
