"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Bell, CheckCheck, RefreshCw } from "lucide-react";
import { api, shortDate } from "@/lib/client";

type Notice = { id:string; title:string; category:string; severity:"info"|"warning"|"critical"; date:string|null; href:string; read:boolean };
const dots={info:"bg-blue-500",warning:"bg-amber-500",critical:"bg-red-500"};

export function NotificationCenter(){
  const[open,setOpen]=useState(false),[notices,setNotices]=useState<Notice[]>([]),[unread,setUnread]=useState(0),[loading,setLoading]=useState(true),[filter,setFilter]=useState<"all"|"unread"|"critical">("all"),[updatedAt,setUpdatedAt]=useState("");
  const ref=useRef<HTMLDivElement>(null);
  async function load(){setLoading(true);try{const result=await api<{notifications:Notice[];unreadCount:number;generatedAt:string}>("/api/notifications");setNotices(result.notifications);setUnread(result.unreadCount);setUpdatedAt(result.generatedAt);}catch{setNotices([]);setUnread(0);}finally{setLoading(false);}}
  useEffect(()=>{load();const timer=setInterval(load,60000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{const close=(event:MouseEvent)=>{if(!ref.current?.contains(event.target as Node))setOpen(false);};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close);},[]);
  async function markRead(key:string){await api("/api/notifications/read",{method:"POST",body:JSON.stringify({notificationKey:key})});setNotices(current=>current.map(item=>item.id===key?{...item,read:true}:item));setUnread(value=>Math.max(0,value-1));}
  async function markAll(){const keys=notices.filter(item=>!item.read).map(item=>item.id);if(!keys.length)return;await api("/api/notifications/read-all",{method:"POST",body:JSON.stringify({notificationKeys:keys})});setNotices(current=>current.map(item=>({...item,read:true})));setUnread(0);}
  const visible=notices.filter(item=>filter==="all"||(filter==="unread"&&!item.read)||(filter==="critical"&&item.severity==="critical"));
  return <div ref={ref} className="relative"><button aria-label="Notifications" onClick={()=>setOpen(!open)} className="relative rounded-xl border border-stone-200 p-2.5 hover:bg-stone-50"><Bell size={18}/>{unread>0&&<span className="absolute -right-1.5 -top-1.5 min-w-5 rounded-full bg-red-600 px-1 text-[10px] font-bold leading-5 text-white">{Math.min(unread,99)}</span>}</button>{open&&<div className="absolute right-0 z-50 mt-2 w-[min(92vw,430px)] overflow-hidden rounded-2xl border bg-white shadow-2xl animate-scale-in"><div className="flex items-center justify-between border-b p-4"><div><h2 className="font-semibold">Notifications</h2><p className="text-xs text-stone-500">{unread} unread · {updatedAt?`last synced ${new Date(updatedAt).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})}`:"syncing"}</p></div><div className="flex gap-1"><button title="Mark all as read" onClick={markAll} disabled={!unread} className="rounded-lg p-2 hover:bg-stone-100"><CheckCheck size={17}/></button><button title="Refresh" onClick={load} className="rounded-lg p-2 hover:bg-stone-100"><RefreshCw size={16} className={loading?"animate-spin":""}/></button></div></div><div className="flex gap-1 border-b p-2">{(["all","unread","critical"] as const).map(tab=><button key={tab} onClick={()=>setFilter(tab)} className={`rounded-lg px-3 py-1.5 text-xs font-semibold capitalize ${filter===tab?"bg-wine text-white":"text-stone-500 hover:bg-stone-100"}`}>{tab}</button>)}</div><div className="max-h-[62vh] divide-y overflow-y-auto">{loading&&!notices.length?<div className="space-y-2 p-4">{[1,2,3].map(item=><div key={item} className="h-16 animate-pulse rounded-xl bg-stone-100"/>)}</div>:visible.length?visible.map(notice=><div key={notice.id} className={`flex gap-3 p-4 ${notice.read?"bg-white opacity-70":"bg-stone-50/70"}`}><span className={`mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full ${dots[notice.severity]}`}/><Link href={notice.href} onClick={()=>{markRead(notice.id);setOpen(false);}} className="min-w-0 flex-1"><p className="text-sm font-medium leading-snug">{notice.title}</p><p className="mt-1 text-xs text-stone-400">{notice.category}{notice.date?` · ${shortDate(notice.date)}`:""}</p></Link>{!notice.read&&<button onClick={()=>markRead(notice.id)} className="self-start rounded px-2 py-1 text-[10px] font-bold text-wine hover:bg-wine/5">Read</button>}</div>):<p className="p-8 text-center text-sm text-stone-400">No notifications for your current role in this view.</p>}</div></div>}</div>;
}
